### ISSUE TITLE
Mistake in Miscellaneous2014.java

### ISSUE THREAD

**Issue by Marti2203** [t0xicdream/UltimateTestCollection2IP90#1]
```
    /*
     * The local variables for this program are
     * Inside the Course class & methods inside this class only:
     * grades, title;
     * Inside the method accessible only:
     * grade, i (from the for element)
     */
```
The local variables are grade, i and threshold if we count parameters.

**Comment by jonibim** [comment]
The exercise is ambiguous if we should count the parameters as local variables too. The exercise states that:

> Mention all the local variables (and the local variables only) in this program

But for the sake of being correct, I add an explanation 👍
