### ISSUE TITLE
Misc2015V2.java

### ISSUE THREAD

**Issue by Marti2203** [t0xicdream/UltimateTestCollection2IP90#3]
Question 1 - ```False. There can be many methods called as long
     * they share different parameters``` There can be many methods called foo as long as they have a different __signature__ name + parameter list.

**Comment by Marti2203** [comment]
Question 2 - This is so strangely defined that I have no words.

**Comment by jonibim** [comment]
Fixed the issue with better clarification and provided an understandable example for question 2
