### ISSUE TITLE
Misc2017 

### ISSUE THREAD

**Issue by Marti2203** [t0xicdream/UltimateTestCollection2IP90#4]
Question 1 - Same issue as Question 1 in #3 
Question 2 - here we have 2 different types of rules. 
1) A and B are primitive types so we can have a being upcasted to B
2) A and B are reference types (objects) so either A has to be a subclass of B

**Comment by Marti2203** [comment]
Quesiton 3 - Mention it is recursive and don't use the variables sum and ARRAY_LENGTH. The former makes the code kindda convoluted while the latter is unneeded.
Same thing qualifies for Question 4.

**Comment by Marti2203** [comment]
V2 Power method does not show where the holes are.

**Comment by jonibim** [comment]
> * A and B are primitive types so we can have a being upcasted to B
> * A and B are reference types (objects) so either A has to be a subclass of B

Fixed the issue. That's a better definiton!

**Comment by jonibim** [comment]
> Quesiton 3 - Mention it is recursive and don't use the variables sum and ARRAY_LENGTH. The former makes the code kindda convoluted while the latter is unneeded.
> Same thing qualifies for Question 4.

Yes, added a new answer which is simplier but also kept the old one because it may be more understandable for those who are new to recursion

**Comment by jonibim** [comment]
> V2 Power method does not show where the holes are.

That is not needed. The holes are specified in the PDF Exam file
